<?php
	/**
	 * Magebit_Editcustomoption
	 *
	 * Magento extension
	 *
	 * NOTICE OF LICENSE
	 * Magento is subject to the Open Software License (OSL 3.0)
	 *
	 * @author      Nagy Attila<nagyattila.dev@gmail.com>
	 * @category    Magebit
	 * @package     Magebit_Editcustomoption
	 * @copyright
	 * @link
	 * @license
	 * @version     0.1.0
	 */
?>
<?php $_order = $this->getOrder() ?>
<div id="custom_overlay"></div>
<div class="grid np">
	<div class="hor-scroll">
		<table cellspacing="0" class="data order-tables">
			<col/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<col width="1"/>
			<thead>
			<tr class="headings">
				<th><?php echo $this->helper( 'sales' )->__( 'Product' ) ?></th>
				<th><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Item Status' ) ?></span></th>
				<th><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Original Price' ) ?></span></th>
				<th><?php echo $this->helper( 'sales' )->__( 'Price' ) ?></th>
				<th class="a-center"><?php echo $this->helper( 'sales' )->__( 'Qty' ) ?></th>
				<th><?php echo $this->helper( 'sales' )->__( 'Subtotal' ) ?></th>
				<th><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Tax Amount' ) ?></span></th>
				<th><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Tax Percent' ) ?></span></th>
				<th><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Discount Amount' ) ?></span></th>
				<th class="nobr"><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Row Total' ) ?></span></th>
				<th class="last"><span class="nobr"><?php echo $this->helper( 'sales' )->__( 'Action' ) ?></span></th>
			</tr>
			</thead>
			<?php $_items = $this->getItemsCollection() ?>
			<?php $i = 0;
				foreach( $_items as $_item ): ?>
					<div id="product_<?php echo $_item->getProductId() ?>" class="custom-modal"></div>
					<?php if( $_item->getParentItem() ) continue;
					else $i++; ?>
					<tbody class="<?php echo $i % 2 ? 'even' : 'odd' ?>">
					<?php echo $this->getItemHtml( $_item ) ?>
					<?php echo $this->getItemExtraInfoHtml( $_item ) ?>
					</tbody>
				<?php endforeach; ?>
		</table>
	</div>
</div><br/>

<script type="text/javascript">

	function loadModal(url, prodId, orderId) {
		form_key = window.FORM_KEY;
		new Ajax.Request(url, {
			method: 'post',
			asynchronous: true,
			evalScripts: false,
			parameters: {prodId: prodId, orderId: orderId},
			onComplete: function (req) {
				Element.hide('loading-mask');
				$('custom_overlay').setStyle({display: 'block'})
				$('product_' + prodId).setStyle({display: 'block'})
				if (req.responseText == 'n') {
					alert('Invalid Request');
				} else {
					$('product_' + prodId).innerHTML = req.responseText;

				}
			}
		});
	}

	function parentHide(id) {
		$('custom_overlay').setStyle({display: 'none'})
		$('product_' + id).setStyle({display: 'none'})
	}
</script>
